### ISSUE TITLE
Incorrect number of results on large graph and homomorphic matching

### ISSUE THREAD

**Issue by szarnyasg** [RapidsAtHKUST/RapidMatch#1]
Hi,

Thanks for this project, it looks super interesting and influential!

I have been experimenting with the LDBC data set and some simple subgraph queries and ran into a potential bug.

I use graph instances based on the LDBC SF3 and SF10 data sets:
* https://www.dropbox.com/s/i0rmhzc7etkmh8a/ldbc-3.graph.zst?dl=0
* https://www.dropbox.com/s/ckm5k3cq5ur88gw/ldbc-10.graph.zst?dl=0

I changed two flags before compiling RapidMatch: https://github.com/szarnyasg/RapidMatch/commit/c3cab52c78f1d1f137deed870a9db23731c23ca3

```
#define RELATION_STRUCTURE 2
#define HOMOMORPHISM
```

My query graph is as follows:

```
t 4 4
v 0 0 2
v 1 0 2
v 2 5 2
v 3 6 2
e 0 1
e 1 2
e 2 3
e 3 0
```

The query is based on the LDBC SNB queries. Its pattern looks as follows:
![image](https://user-images.githubusercontent.com/1402801/111905846-0ae82400-8a4e-11eb-9f48-af4e436ff5ec.png)

I cross-validated the implementation of this query against two other (closed-source) systems, an RDBMS and a graph analytics engine.

On SF3, I consistently get `3340333` from all systems.

On SF10, the expected result of `11407928` (returned by the two other systems). RapidMatch returns different results on each run.

For example, I get these results:

```
Load graphs time (seconds): 76.772033
Query time (seconds): 62.493771
#Embeddings: 5346976
End.
```
```
Load graphs time (seconds): 79.109461
Query time (seconds): 62.303299
#Embeddings: 5851058
End.
```
```
Load graphs time (seconds): 79.178901
Query time (seconds): 62.080454
#Embeddings: 5730862
End.
```

The machine I'm running on has an Intel Xeon 8272CL CPU, 378GiB RAM, and runs Ubuntu 20.04 with GCC 9.3.0.

**Comment by shixuansun** [comment]
> Hi,
> 
> Thanks for this project, it looks super interesting and influential!
> 
> I have been experimenting with the LDBC data set and some simple subgraph queries and ran into a potential bug.
> 
> I use graph instances based on the LDBC SF3 and SF10 data sets:
> 
> * https://www.dropbox.com/s/i0rmhzc7etkmh8a/ldbc-3.graph.zst?dl=0
> * https://www.dropbox.com/s/ckm5k3cq5ur88gw/ldbc-10.graph.zst?dl=0
> 
> I changed two flags before compiling RapidMatch: [szarnyasg@c3cab52](https://github.com/szarnyasg/RapidMatch/commit/c3cab52c78f1d1f137deed870a9db23731c23ca3)
> 
> ```
> #define RELATION_STRUCTURE 2
> #define HOMOMORPHISM
> ```
> 
> My query graph is as follows:
> 
> ```
> t 4 4
> v 0 0 2
> v 1 0 2
> v 2 5 2
> v 3 6 2
> e 0 1
> e 1 2
> e 2 3
> e 3 0
> ```
> 
> The query is based on the LDBC SNB queries. Its pattern looks as follows:
> ![image](https://user-images.githubusercontent.com/1402801/111905846-0ae82400-8a4e-11eb-9f48-af4e436ff5ec.png)
> 
> I cross-validated the implementation of this query against two other (closed-source) systems, an RDBMS and a graph analytics engine.
> 
> On SF3, I consistently get `3340333` from all systems.
> 
> On SF10, the expected result of `11407928` (returned by the two other systems). RapidMatch returns different results on each run.
> 
> For example, I get these results:
> 
> ```
> Load graphs time (seconds): 76.772033
> Query time (seconds): 62.493771
> #Embeddings: 5346976
> End.
> ```
> 
> ```
> Load graphs time (seconds): 79.109461
> Query time (seconds): 62.303299
> #Embeddings: 5851058
> End.
> ```
> 
> ```
> Load graphs time (seconds): 79.178901
> Query time (seconds): 62.080454
> #Embeddings: 5730862
> End.
> ```
> 
> The machine I'm running on has an Intel Xeon 8272CL CPU, 378GiB RAM, and runs Ubuntu 20.04 with GCC 9.3.0.

Hi,

Thanks for your interest in our project.

To find homomorphisms, you need to disable the failing set pruning technique by commenting out "FAILING_SET_PRUNING" in config.h because this optimization is designed for enumerating isomorphisms. Moreover, you need to increase the time limit for the query because the program will terminate the query if it cannot be completed within the time limit. In my machine, the query that you provide takes around 70 seconds. So you can set the time limit to 120 seconds by "-time_limit 120".

The following is the log.

```zsh
Load graphs time (seconds): 39.103812
Query time (seconds): 70.279089
#Embeddings: 11407928
End.
```

Hope this helps. I will update the README file to clarify the problem.

Finally, thanks for your question.

**Comment by szarnyasg** [comment]
@shixuansun Thanks for the prompt reply! With the change in the configuration and by increasing the time limit, I could derive the correct answer.
