### ISSUE TITLE
使用过程中的一些问题

### ISSUE THREAD

**Issue by orilian** [RapidsAtHKUST/RapidMatch#4]
Hello!您好
我在使用RapidMatch的过程中发现：
对于同构匹配，我调用Playground.out查看匹配结果时会得到正确的结果

![image](https://user-images.githubusercontent.com/73419752/181677616-b1e6629b-4f0c-45f9-9a0a-f30cef6e96c4.png)

但是在同态匹配时，得到的结果数量是对的；但所有嵌入结果显示都为0，不知道是怎么回事

![result](https://user-images.githubusercontent.com/73419752/181677711-b191bd74-3ca7-489e-9359-21c193e3dd57.PNG)

这是我的设置
![config](https://user-images.githubusercontent.com/73419752/181677735-f6ef8917-2d94-42ab-a6a9-0df4928602db.PNG)

我的查询图是

t 5 7
v 0 0 2
v 1 1 3
v 2 1 3
v 3 2 3
v 4 3 3
e 0 1
e 0 2
e 1 3
e 1 4
e 2 3
e 2 4
e 3 4

数据图是
t 4 4
v 0 0 1
v 1 1 3
v 2 2 2
v 3 3 2
e 0 1
e 1 2
e 1 3
e 2 3

另外，我还想请教下RapidMatch对于有向图的子图查询和有边标签的图的子图查询是可以实现的吗，因为我对这两类子图查询进行了简单的测试，结果是不行的……

望您不吝赐教~

**Comment by shixuansun** [comment]
Hi，

1. 在Homomorphism情况下没有输出，是因为输出代码没有添加到HOMOMORPHISM模式下，leapfrogtriejoin.cpp 136-143行是在HOMOMORPHISM模式下找到embedding，可以尝试把输出代码（177-186行）添加到相应位置。或者等我周一修复一下提交上去。另外，如果要测试性能，要把output disable，否则结果copy操作可能会占用较长时间。

2. RapidMatch现在版本的实现不支持有向图和有edge label的图，改动方法是在scan edge的时候基于边的方向和edge label进行过滤，不过这也需要对graph类进行修改，使其能够存储边的方向和label。

如果有进一步问题，可以随时联系我。谢谢！

**Comment by orilian** [comment]
非常感谢您的回复！
我尝试简单地把输出代码copy到相应位置，如下
![code](https://user-images.githubusercontent.com/73419752/181871564-243b2e59-125d-4688-8569-3e0e530f8d07.png)
对于这对查询图和数据图，我得到了正确的输出结果
![rightresult](https://user-images.githubusercontent.com/73419752/181871583-c7b67aa4-7374-44f7-a1bb-2a631530b989.png)

但是对于其他的子图查询，仍然是之前的问题，
![failresult](https://user-images.githubusercontent.com/73419752/181871591-ff406fff-07de-4629-a75a-1045a31607dd.png)

……不好意思，我还是等您上传修复的代码吧。

再次感谢您的回复！

**Comment by shixuansun** [comment]
Hi，不好意思，最近有几个deadline在赶，更新晚了。

现在已经为HOMOMORPHISM添加了输出功能，请你试一下在你的test case上是否可以。另外，如果使用HOMOMORPHISM，需要把FAILING_SET这个优化关掉，因为这对ISOMORPHISM才有效。

如果有进一步问题，可以随时联系我。

**Comment by orilian** [comment]
十分感谢您的耐心回复，没有其他问题的话我将关闭这个issue，再次感谢
